export const SalaryStreamingABI = [
  {
    type: "event",
    name: "StreamCreated",
    inputs: [
      { name: "streamId", type: "uint256", indexed: true },
      { name: "recipient", type: "address", indexed: true },
      { name: "intervalType", type: "uint8", indexed: true },
    ],
  },
  {
    type: "event",
    name: "StreamPaused",
    inputs: [
      { name: "recipient", type: "address", indexed: true },
      { name: "intervalType", type: "uint8", indexed: true },
    ],
  },
  {
    type: "event",
    name: "StreamResumed",
    inputs: [
      { name: "recipient", type: "address", indexed: true },
      { name: "intervalType", type: "uint8", indexed: true },
    ],
  },
  {
    type: "event",
    name: "StreamStopped",
    inputs: [
      { name: "recipient", type: "address", indexed: true },
      { name: "intervalType", type: "uint8", indexed: true },
    ],
  },
  {
    type: "event",
    name: "disbursementSuccessful",
    inputs: [
      { name: "sender", type: "address", indexed: false },
      { name: "recipient", type: "address", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "function",
    name: "fees",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "createStream",
    stateMutability: "nonpayable",
    inputs: [
      {
        name: "_streamDetails",
        type: "tuple[]",
        components: [
          { name: "name", type: "string" },
          { name: "recipient", type: "address" },
          { name: "amount", type: "uint256" },
        ],
      },
      { name: "intervalType", type: "uint8" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "getAllDailyStreams",
    stateMutability: "view",
    inputs: [],
    outputs: [
      {
        type: "tuple[]",
        components: [
          { name: "id", type: "uint256" },
          { name: "recipient", type: "address" },
          { name: "amount", type: "uint256" },
          { name: "lastPayment", type: "uint256" },
          { name: "startTime", type: "uint256" },
          { name: "intervalType", type: "uint8" },
          { name: "active", type: "bool" },
          { name: "name", type: "string" },
          { name: "streamOwner", type: "address" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "getAllMonthlyStreams",
    stateMutability: "view",
    inputs: [],
    outputs: [
      {
        type: "tuple[]",
        components: [
          { name: "id", type: "uint256" },
          { name: "recipient", type: "address" },
          { name: "amount", type: "uint256" },
          { name: "lastPayment", type: "uint256" },
          { name: "startTime", type: "uint256" },
          { name: "intervalType", type: "uint8" },
          { name: "active", type: "bool" },
          { name: "name", type: "string" },
          { name: "streamOwner", type: "address" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "pauseDailyStream",
    stateMutability: "nonpayable",
    inputs: [{ name: "_streamId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "pauseMonthlyStream",
    stateMutability: "nonpayable",
    inputs: [{ name: "_streamId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "resumeDailyStream",
    stateMutability: "nonpayable",
    inputs: [{ name: "_streamId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "resumeMonthlyStream",
    stateMutability: "nonpayable",
    inputs: [{ name: "_streamId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "disburseDaily",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "disburseMonthly",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "streamIdsByAddress",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "streamsById",
    stateMutability: "view",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [
      {
        type: "tuple",
        components: [
          { name: "id", type: "uint256" },
          { name: "recipient", type: "address" },
          { name: "amount", type: "uint256" },
          { name: "lastPayment", type: "uint256" },
          { name: "startTime", type: "uint256" },
          { name: "intervalType", type: "uint8" },
          { name: "active", type: "bool" },
          { name: "name", type: "string" },
          { name: "streamOwner", type: "address" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "modalContract",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
] as const
