FROM oven/bun:1.2

WORKDIR /app

RUN apt-get update -y \
	&& apt-get install -y --no-install-recommends openssl libssl3 ca-certificates \
	&& rm -rf /var/lib/apt/lists/*

COPY package.json bun.lock* ./
RUN bun install --no-progress

COPY . .

EXPOSE 3000

CMD ["bun", "run", "src/server.ts"]
